/**
 * CV4CREW
 * API to fill CV for crewing agencies
 *
 * OpenAPI spec version: 1.0.0
 * Contact: eugene.kondrashev@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 3.3.4
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Cv4Crew) {
      root.Cv4Crew = {};
    }
    root.Cv4Crew.Countries = factory(root.Cv4Crew.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';


  /**
   * Enum class Countries.
   * @enum {}
   * @readonly
   */
  var exports = {
    /**
     * value: "afghanistan"
     * @const
     */
    "afghanistan": "afghanistan",
    /**
     * value: "albania"
     * @const
     */
    "albania": "albania",
    /**
     * value: "algeria"
     * @const
     */
    "algeria": "algeria",
    /**
     * value: "andorra"
     * @const
     */
    "andorra": "andorra",
    /**
     * value: "angola"
     * @const
     */
    "angola": "angola",
    /**
     * value: "antigua & deps"
     * @const
     */
    "antigua &amp; deps": "antigua & deps",
    /**
     * value: "argentina"
     * @const
     */
    "argentina": "argentina",
    /**
     * value: "armenia"
     * @const
     */
    "armenia": "armenia",
    /**
     * value: "australia"
     * @const
     */
    "australia": "australia",
    /**
     * value: "austria"
     * @const
     */
    "austria": "austria",
    /**
     * value: "azerbaijan"
     * @const
     */
    "azerbaijan": "azerbaijan",
    /**
     * value: "bahamas"
     * @const
     */
    "bahamas": "bahamas",
    /**
     * value: "bahrain"
     * @const
     */
    "bahrain": "bahrain",
    /**
     * value: "bangladesh"
     * @const
     */
    "bangladesh": "bangladesh",
    /**
     * value: "barbados"
     * @const
     */
    "barbados": "barbados",
    /**
     * value: "belarus"
     * @const
     */
    "belarus": "belarus",
    /**
     * value: "belgium"
     * @const
     */
    "belgium": "belgium",
    /**
     * value: "belize"
     * @const
     */
    "belize": "belize",
    /**
     * value: "benin"
     * @const
     */
    "benin": "benin",
    /**
     * value: "bhutan"
     * @const
     */
    "bhutan": "bhutan",
    /**
     * value: "bolivia"
     * @const
     */
    "bolivia": "bolivia",
    /**
     * value: "bosnia herzegovina"
     * @const
     */
    "bosnia herzegovina": "bosnia herzegovina",
    /**
     * value: "botswana"
     * @const
     */
    "botswana": "botswana",
    /**
     * value: "brazil"
     * @const
     */
    "brazil": "brazil",
    /**
     * value: "brunei"
     * @const
     */
    "brunei": "brunei",
    /**
     * value: "bulgaria"
     * @const
     */
    "bulgaria": "bulgaria",
    /**
     * value: "burkina"
     * @const
     */
    "burkina": "burkina",
    /**
     * value: "burundi"
     * @const
     */
    "burundi": "burundi",
    /**
     * value: "cambodia"
     * @const
     */
    "cambodia": "cambodia",
    /**
     * value: "cameroon"
     * @const
     */
    "cameroon": "cameroon",
    /**
     * value: "canada"
     * @const
     */
    "canada": "canada",
    /**
     * value: "cape verde"
     * @const
     */
    "cape verde": "cape verde",
    /**
     * value: "central african rep"
     * @const
     */
    "central african rep": "central african rep",
    /**
     * value: "chad"
     * @const
     */
    "chad": "chad",
    /**
     * value: "chile"
     * @const
     */
    "chile": "chile",
    /**
     * value: "china"
     * @const
     */
    "china": "china",
    /**
     * value: "colombia"
     * @const
     */
    "colombia": "colombia",
    /**
     * value: "comoros"
     * @const
     */
    "comoros": "comoros",
    /**
     * value: "congo"
     * @const
     */
    "congo": "congo",
    /**
     * value: "congo {democratic rep}"
     * @const
     */
    "congo {democratic rep}": "congo {democratic rep}",
    /**
     * value: "costa rica"
     * @const
     */
    "costa rica": "costa rica",
    /**
     * value: "croatia"
     * @const
     */
    "croatia": "croatia",
    /**
     * value: "cuba"
     * @const
     */
    "cuba": "cuba",
    /**
     * value: "cyprus"
     * @const
     */
    "cyprus": "cyprus",
    /**
     * value: "czech republic"
     * @const
     */
    "czech republic": "czech republic",
    /**
     * value: "denmark"
     * @const
     */
    "denmark": "denmark",
    /**
     * value: "djibouti"
     * @const
     */
    "djibouti": "djibouti",
    /**
     * value: "dominica"
     * @const
     */
    "dominica": "dominica",
    /**
     * value: "dominican republic"
     * @const
     */
    "dominican republic": "dominican republic",
    /**
     * value: "east timor"
     * @const
     */
    "east timor": "east timor",
    /**
     * value: "ecuador"
     * @const
     */
    "ecuador": "ecuador",
    /**
     * value: "egypt"
     * @const
     */
    "egypt": "egypt",
    /**
     * value: "el salvador"
     * @const
     */
    "el salvador": "el salvador",
    /**
     * value: "equatorial guinea"
     * @const
     */
    "equatorial guinea": "equatorial guinea",
    /**
     * value: "eritrea"
     * @const
     */
    "eritrea": "eritrea",
    /**
     * value: "estonia"
     * @const
     */
    "estonia": "estonia",
    /**
     * value: "ethiopia"
     * @const
     */
    "ethiopia": "ethiopia",
    /**
     * value: "fiji"
     * @const
     */
    "fiji": "fiji",
    /**
     * value: "finland"
     * @const
     */
    "finland": "finland",
    /**
     * value: "france"
     * @const
     */
    "france": "france",
    /**
     * value: "gabon"
     * @const
     */
    "gabon": "gabon",
    /**
     * value: "gambia"
     * @const
     */
    "gambia": "gambia",
    /**
     * value: "georgia"
     * @const
     */
    "georgia": "georgia",
    /**
     * value: "germany"
     * @const
     */
    "germany": "germany",
    /**
     * value: "ghana"
     * @const
     */
    "ghana": "ghana",
    /**
     * value: "greece"
     * @const
     */
    "greece": "greece",
    /**
     * value: "grenada"
     * @const
     */
    "grenada": "grenada",
    /**
     * value: "guatemala"
     * @const
     */
    "guatemala": "guatemala",
    /**
     * value: "guinea"
     * @const
     */
    "guinea": "guinea",
    /**
     * value: "guinea-bissau"
     * @const
     */
    "guinea-bissau": "guinea-bissau",
    /**
     * value: "guyana"
     * @const
     */
    "guyana": "guyana",
    /**
     * value: "haiti"
     * @const
     */
    "haiti": "haiti",
    /**
     * value: "honduras"
     * @const
     */
    "honduras": "honduras",
    /**
     * value: "hungary"
     * @const
     */
    "hungary": "hungary",
    /**
     * value: "iceland"
     * @const
     */
    "iceland": "iceland",
    /**
     * value: "india"
     * @const
     */
    "india": "india",
    /**
     * value: "indonesia"
     * @const
     */
    "indonesia": "indonesia",
    /**
     * value: "iran"
     * @const
     */
    "iran": "iran",
    /**
     * value: "iraq"
     * @const
     */
    "iraq": "iraq",
    /**
     * value: "ireland {republic}"
     * @const
     */
    "ireland {republic}": "ireland {republic}",
    /**
     * value: "israel"
     * @const
     */
    "israel": "israel",
    /**
     * value: "italy"
     * @const
     */
    "italy": "italy",
    /**
     * value: "ivory coast"
     * @const
     */
    "ivory coast": "ivory coast",
    /**
     * value: "jamaica"
     * @const
     */
    "jamaica": "jamaica",
    /**
     * value: "japan"
     * @const
     */
    "japan": "japan",
    /**
     * value: "jordan"
     * @const
     */
    "jordan": "jordan",
    /**
     * value: "kazakhstan"
     * @const
     */
    "kazakhstan": "kazakhstan",
    /**
     * value: "kenya"
     * @const
     */
    "kenya": "kenya",
    /**
     * value: "kiribati"
     * @const
     */
    "kiribati": "kiribati",
    /**
     * value: "korea north"
     * @const
     */
    "korea north": "korea north",
    /**
     * value: "korea south"
     * @const
     */
    "korea south": "korea south",
    /**
     * value: "kosovo"
     * @const
     */
    "kosovo": "kosovo",
    /**
     * value: "kuwait"
     * @const
     */
    "kuwait": "kuwait",
    /**
     * value: "kyrgyzstan"
     * @const
     */
    "kyrgyzstan": "kyrgyzstan",
    /**
     * value: "laos"
     * @const
     */
    "laos": "laos",
    /**
     * value: "latvia"
     * @const
     */
    "latvia": "latvia",
    /**
     * value: "lebanon"
     * @const
     */
    "lebanon": "lebanon",
    /**
     * value: "lesotho"
     * @const
     */
    "lesotho": "lesotho",
    /**
     * value: "liberia"
     * @const
     */
    "liberia": "liberia",
    /**
     * value: "libya"
     * @const
     */
    "libya": "libya",
    /**
     * value: "liechtenstein"
     * @const
     */
    "liechtenstein": "liechtenstein",
    /**
     * value: "lithuania"
     * @const
     */
    "lithuania": "lithuania",
    /**
     * value: "luxembourg"
     * @const
     */
    "luxembourg": "luxembourg",
    /**
     * value: "macedonia"
     * @const
     */
    "macedonia": "macedonia",
    /**
     * value: "madagascar"
     * @const
     */
    "madagascar": "madagascar",
    /**
     * value: "malawi"
     * @const
     */
    "malawi": "malawi",
    /**
     * value: "malaysia"
     * @const
     */
    "malaysia": "malaysia",
    /**
     * value: "maldives"
     * @const
     */
    "maldives": "maldives",
    /**
     * value: "mali"
     * @const
     */
    "mali": "mali",
    /**
     * value: "malta"
     * @const
     */
    "malta": "malta",
    /**
     * value: "marshall islands"
     * @const
     */
    "marshall islands": "marshall islands",
    /**
     * value: "mauritania"
     * @const
     */
    "mauritania": "mauritania",
    /**
     * value: "mauritius"
     * @const
     */
    "mauritius": "mauritius",
    /**
     * value: "mexico"
     * @const
     */
    "mexico": "mexico",
    /**
     * value: "micronesia"
     * @const
     */
    "micronesia": "micronesia",
    /**
     * value: "moldova"
     * @const
     */
    "moldova": "moldova",
    /**
     * value: "monaco"
     * @const
     */
    "monaco": "monaco",
    /**
     * value: "mongolia"
     * @const
     */
    "mongolia": "mongolia",
    /**
     * value: "montenegro"
     * @const
     */
    "montenegro": "montenegro",
    /**
     * value: "morocco"
     * @const
     */
    "morocco": "morocco",
    /**
     * value: "mozambique"
     * @const
     */
    "mozambique": "mozambique",
    /**
     * value: "myanmar, {burma}"
     * @const
     */
    "myanmar, {burma}": "myanmar, {burma}",
    /**
     * value: "namibia"
     * @const
     */
    "namibia": "namibia",
    /**
     * value: "nauru"
     * @const
     */
    "nauru": "nauru",
    /**
     * value: "nepal"
     * @const
     */
    "nepal": "nepal",
    /**
     * value: "netherlands"
     * @const
     */
    "netherlands": "netherlands",
    /**
     * value: "new zealand"
     * @const
     */
    "new zealand": "new zealand",
    /**
     * value: "nicaragua"
     * @const
     */
    "nicaragua": "nicaragua",
    /**
     * value: "niger"
     * @const
     */
    "niger": "niger",
    /**
     * value: "nigeria"
     * @const
     */
    "nigeria": "nigeria",
    /**
     * value: "norway"
     * @const
     */
    "norway": "norway",
    /**
     * value: "oman"
     * @const
     */
    "oman": "oman",
    /**
     * value: "pakistan"
     * @const
     */
    "pakistan": "pakistan",
    /**
     * value: "palau"
     * @const
     */
    "palau": "palau",
    /**
     * value: "panama"
     * @const
     */
    "panama": "panama",
    /**
     * value: "papua new guinea"
     * @const
     */
    "papua new guinea": "papua new guinea",
    /**
     * value: "paraguay"
     * @const
     */
    "paraguay": "paraguay",
    /**
     * value: "peru"
     * @const
     */
    "peru": "peru",
    /**
     * value: "philippines"
     * @const
     */
    "philippines": "philippines",
    /**
     * value: "poland"
     * @const
     */
    "poland": "poland",
    /**
     * value: "portugal"
     * @const
     */
    "portugal": "portugal",
    /**
     * value: "qatar"
     * @const
     */
    "qatar": "qatar",
    /**
     * value: "romania"
     * @const
     */
    "romania": "romania",
    /**
     * value: "russian federation"
     * @const
     */
    "russian federation": "russian federation",
    /**
     * value: "rwanda"
     * @const
     */
    "rwanda": "rwanda",
    /**
     * value: "st kitts & nevis"
     * @const
     */
    "st kitts &amp; nevis": "st kitts & nevis",
    /**
     * value: "st lucia"
     * @const
     */
    "st lucia": "st lucia",
    /**
     * value: "saint vincent & the grenadines"
     * @const
     */
    "saint vincent &amp; the grenadines": "saint vincent & the grenadines",
    /**
     * value: "samoa"
     * @const
     */
    "samoa": "samoa",
    /**
     * value: "san marino"
     * @const
     */
    "san marino": "san marino",
    /**
     * value: "sao tome & principe"
     * @const
     */
    "sao tome &amp; principe": "sao tome & principe",
    /**
     * value: "saudi arabia"
     * @const
     */
    "saudi arabia": "saudi arabia",
    /**
     * value: "senegal"
     * @const
     */
    "senegal": "senegal",
    /**
     * value: "serbia"
     * @const
     */
    "serbia": "serbia",
    /**
     * value: "seychelles"
     * @const
     */
    "seychelles": "seychelles",
    /**
     * value: "sierra leone"
     * @const
     */
    "sierra leone": "sierra leone",
    /**
     * value: "singapore"
     * @const
     */
    "singapore": "singapore",
    /**
     * value: "slovakia"
     * @const
     */
    "slovakia": "slovakia",
    /**
     * value: "slovenia"
     * @const
     */
    "slovenia": "slovenia",
    /**
     * value: "solomon islands"
     * @const
     */
    "solomon islands": "solomon islands",
    /**
     * value: "somalia"
     * @const
     */
    "somalia": "somalia",
    /**
     * value: "south africa"
     * @const
     */
    "south africa": "south africa",
    /**
     * value: "south sudan"
     * @const
     */
    "south sudan": "south sudan",
    /**
     * value: "spain"
     * @const
     */
    "spain": "spain",
    /**
     * value: "sri lanka"
     * @const
     */
    "sri lanka": "sri lanka",
    /**
     * value: "sudan"
     * @const
     */
    "sudan": "sudan",
    /**
     * value: "suriname"
     * @const
     */
    "suriname": "suriname",
    /**
     * value: "swaziland"
     * @const
     */
    "swaziland": "swaziland",
    /**
     * value: "sweden"
     * @const
     */
    "sweden": "sweden",
    /**
     * value: "switzerland"
     * @const
     */
    "switzerland": "switzerland",
    /**
     * value: "syria"
     * @const
     */
    "syria": "syria",
    /**
     * value: "taiwan"
     * @const
     */
    "taiwan": "taiwan",
    /**
     * value: "tajikistan"
     * @const
     */
    "tajikistan": "tajikistan",
    /**
     * value: "tanzania"
     * @const
     */
    "tanzania": "tanzania",
    /**
     * value: "thailand"
     * @const
     */
    "thailand": "thailand",
    /**
     * value: "togo"
     * @const
     */
    "togo": "togo",
    /**
     * value: "tonga"
     * @const
     */
    "tonga": "tonga",
    /**
     * value: "trinidad & tobago"
     * @const
     */
    "trinidad &amp; tobago": "trinidad & tobago",
    /**
     * value: "tunisia"
     * @const
     */
    "tunisia": "tunisia",
    /**
     * value: "turkey"
     * @const
     */
    "turkey": "turkey",
    /**
     * value: "turkmenistan"
     * @const
     */
    "turkmenistan": "turkmenistan",
    /**
     * value: "tuvalu"
     * @const
     */
    "tuvalu": "tuvalu",
    /**
     * value: "uganda"
     * @const
     */
    "uganda": "uganda",
    /**
     * value: "ukraine"
     * @const
     */
    "ukraine": "ukraine",
    /**
     * value: "united arab emirates"
     * @const
     */
    "united arab emirates": "united arab emirates",
    /**
     * value: "united kingdom"
     * @const
     */
    "united kingdom": "united kingdom",
    /**
     * value: "united states"
     * @const
     */
    "united states": "united states",
    /**
     * value: "uruguay"
     * @const
     */
    "uruguay": "uruguay",
    /**
     * value: "uzbekistan"
     * @const
     */
    "uzbekistan": "uzbekistan",
    /**
     * value: "vanuatu"
     * @const
     */
    "vanuatu": "vanuatu",
    /**
     * value: "vatican city"
     * @const
     */
    "vatican city": "vatican city",
    /**
     * value: "venezuela"
     * @const
     */
    "venezuela": "venezuela",
    /**
     * value: "vietnam"
     * @const
     */
    "vietnam": "vietnam",
    /**
     * value: "yemen"
     * @const
     */
    "yemen": "yemen",
    /**
     * value: "zambia"
     * @const
     */
    "zambia": "zambia",
    /**
     * value: "zimbabwe"
     * @const
     */
    "zimbabwe": "zimbabwe"  };

  /**
   * Returns a <code>Countries</code> enum value from a Javascript object name.
   * @param {Object} data The plain JavaScript object containing the name of the enum value.
   * @return {module:model/Countries} The enum <code>Countries</code> value.
   */
  exports.constructFromObject = function(object) {
    return object;
  }

  return exports;
}));


