/**
 * CV4CREW
 * API to fill CV for crewing agencies
 *
 * OpenAPI spec version: 1.0.0
 * Contact: eugene.kondrashev@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 3.3.4
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Cv4Crew) {
      root.Cv4Crew = {};
    }
    root.Cv4Crew.Names = factory(root.Cv4Crew.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';



  /**
   * The Names model module.
   * @module model/Names
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>Names</code>.
   * @alias module:model/Names
   * @class
   * @param first {String} 
   * @param second {String} 
   * @param middle {String} 
   */
  var exports = function(first, second, middle) {
    var _this = this;

    _this['first'] = first;
    _this['second'] = second;
    _this['middle'] = middle;
  };

  /**
   * Constructs a <code>Names</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Names} obj Optional instance to populate.
   * @return {module:model/Names} The populated <code>Names</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('first')) {
        obj['first'] = ApiClient.convertToType(data['first'], 'String');
      }
      if (data.hasOwnProperty('second')) {
        obj['second'] = ApiClient.convertToType(data['second'], 'String');
      }
      if (data.hasOwnProperty('middle')) {
        obj['middle'] = ApiClient.convertToType(data['middle'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {String} first
   */
  exports.prototype['first'] = undefined;
  /**
   * @member {String} second
   */
  exports.prototype['second'] = undefined;
  /**
   * @member {String} middle
   */
  exports.prototype['middle'] = undefined;



  return exports;
}));


