/**
 * CV4CREW
 * API to fill CV for crewing agencies
 *
 * OpenAPI spec version: 1.0.0
 * Contact: eugene.kondrashev@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 3.3.4
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Cv4Crew) {
      root.Cv4Crew = {};
    }
    root.Cv4Crew.Nationalities = factory(root.Cv4Crew.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';


  /**
   * Enum class Nationalities.
   * @enum {}
   * @readonly
   */
  var exports = {
    /**
     * value: "afghan"
     * @const
     */
    "afghan": "afghan",
    /**
     * value: "albanian"
     * @const
     */
    "albanian": "albanian",
    /**
     * value: "algerian"
     * @const
     */
    "algerian": "algerian",
    /**
     * value: "american"
     * @const
     */
    "american": "american",
    /**
     * value: "andorran"
     * @const
     */
    "andorran": "andorran",
    /**
     * value: "angolan"
     * @const
     */
    "angolan": "angolan",
    /**
     * value: "antiguans"
     * @const
     */
    "antiguans": "antiguans",
    /**
     * value: "argentinean"
     * @const
     */
    "argentinean": "argentinean",
    /**
     * value: "armenian"
     * @const
     */
    "armenian": "armenian",
    /**
     * value: "australian"
     * @const
     */
    "australian": "australian",
    /**
     * value: "austrian"
     * @const
     */
    "austrian": "austrian",
    /**
     * value: "azerbaijani"
     * @const
     */
    "azerbaijani": "azerbaijani",
    /**
     * value: "bahamian"
     * @const
     */
    "bahamian": "bahamian",
    /**
     * value: "bahraini"
     * @const
     */
    "bahraini": "bahraini",
    /**
     * value: "bangladeshi"
     * @const
     */
    "bangladeshi": "bangladeshi",
    /**
     * value: "barbadian"
     * @const
     */
    "barbadian": "barbadian",
    /**
     * value: "barbudans"
     * @const
     */
    "barbudans": "barbudans",
    /**
     * value: "batswana"
     * @const
     */
    "batswana": "batswana",
    /**
     * value: "belarusian"
     * @const
     */
    "belarusian": "belarusian",
    /**
     * value: "belgian"
     * @const
     */
    "belgian": "belgian",
    /**
     * value: "belizean"
     * @const
     */
    "belizean": "belizean",
    /**
     * value: "beninese"
     * @const
     */
    "beninese": "beninese",
    /**
     * value: "bhutanese"
     * @const
     */
    "bhutanese": "bhutanese",
    /**
     * value: "bolivian"
     * @const
     */
    "bolivian": "bolivian",
    /**
     * value: "bosnian"
     * @const
     */
    "bosnian": "bosnian",
    /**
     * value: "brazilian"
     * @const
     */
    "brazilian": "brazilian",
    /**
     * value: "british"
     * @const
     */
    "british": "british",
    /**
     * value: "bruneian"
     * @const
     */
    "bruneian": "bruneian",
    /**
     * value: "bulgarian"
     * @const
     */
    "bulgarian": "bulgarian",
    /**
     * value: "burkinabe"
     * @const
     */
    "burkinabe": "burkinabe",
    /**
     * value: "burmese"
     * @const
     */
    "burmese": "burmese",
    /**
     * value: "burundian"
     * @const
     */
    "burundian": "burundian",
    /**
     * value: "cambodian"
     * @const
     */
    "cambodian": "cambodian",
    /**
     * value: "cameroonian"
     * @const
     */
    "cameroonian": "cameroonian",
    /**
     * value: "canadian"
     * @const
     */
    "canadian": "canadian",
    /**
     * value: "cape verdean"
     * @const
     */
    "cape verdean": "cape verdean",
    /**
     * value: "central african"
     * @const
     */
    "central african": "central african",
    /**
     * value: "chadian"
     * @const
     */
    "chadian": "chadian",
    /**
     * value: "chilean"
     * @const
     */
    "chilean": "chilean",
    /**
     * value: "chinese"
     * @const
     */
    "chinese": "chinese",
    /**
     * value: "colombian"
     * @const
     */
    "colombian": "colombian",
    /**
     * value: "comoran"
     * @const
     */
    "comoran": "comoran",
    /**
     * value: "congolese"
     * @const
     */
    "congolese": "congolese",
    /**
     * value: "costa rican"
     * @const
     */
    "costa rican": "costa rican",
    /**
     * value: "croatian"
     * @const
     */
    "croatian": "croatian",
    /**
     * value: "cuban"
     * @const
     */
    "cuban": "cuban",
    /**
     * value: "cypriot"
     * @const
     */
    "cypriot": "cypriot",
    /**
     * value: "czech"
     * @const
     */
    "czech": "czech",
    /**
     * value: "danish"
     * @const
     */
    "danish": "danish",
    /**
     * value: "djibouti"
     * @const
     */
    "djibouti": "djibouti",
    /**
     * value: "dominican"
     * @const
     */
    "dominican": "dominican",
    /**
     * value: "dutch"
     * @const
     */
    "dutch": "dutch",
    /**
     * value: "east timorese"
     * @const
     */
    "east timorese": "east timorese",
    /**
     * value: "ecuadorean"
     * @const
     */
    "ecuadorean": "ecuadorean",
    /**
     * value: "egyptian"
     * @const
     */
    "egyptian": "egyptian",
    /**
     * value: "emirian"
     * @const
     */
    "emirian": "emirian",
    /**
     * value: "equatorial guinean"
     * @const
     */
    "equatorial guinean": "equatorial guinean",
    /**
     * value: "eritrean"
     * @const
     */
    "eritrean": "eritrean",
    /**
     * value: "estonian"
     * @const
     */
    "estonian": "estonian",
    /**
     * value: "ethiopian"
     * @const
     */
    "ethiopian": "ethiopian",
    /**
     * value: "fijian"
     * @const
     */
    "fijian": "fijian",
    /**
     * value: "filipino"
     * @const
     */
    "filipino": "filipino",
    /**
     * value: "finnish"
     * @const
     */
    "finnish": "finnish",
    /**
     * value: "french"
     * @const
     */
    "french": "french",
    /**
     * value: "gabonese"
     * @const
     */
    "gabonese": "gabonese",
    /**
     * value: "gambian"
     * @const
     */
    "gambian": "gambian",
    /**
     * value: "georgian"
     * @const
     */
    "georgian": "georgian",
    /**
     * value: "german"
     * @const
     */
    "german": "german",
    /**
     * value: "ghanaian"
     * @const
     */
    "ghanaian": "ghanaian",
    /**
     * value: "greek"
     * @const
     */
    "greek": "greek",
    /**
     * value: "grenadian"
     * @const
     */
    "grenadian": "grenadian",
    /**
     * value: "guatemalan"
     * @const
     */
    "guatemalan": "guatemalan",
    /**
     * value: "guinea:bissauan"
     * @const
     */
    "guinea:bissauan": "guinea:bissauan",
    /**
     * value: "guinean"
     * @const
     */
    "guinean": "guinean",
    /**
     * value: "guyanese"
     * @const
     */
    "guyanese": "guyanese",
    /**
     * value: "haitian"
     * @const
     */
    "haitian": "haitian",
    /**
     * value: "herzegovinian"
     * @const
     */
    "herzegovinian": "herzegovinian",
    /**
     * value: "honduran"
     * @const
     */
    "honduran": "honduran",
    /**
     * value: "hungarian"
     * @const
     */
    "hungarian": "hungarian",
    /**
     * value: "icelander"
     * @const
     */
    "icelander": "icelander",
    /**
     * value: "indian"
     * @const
     */
    "indian": "indian",
    /**
     * value: "indonesian"
     * @const
     */
    "indonesian": "indonesian",
    /**
     * value: "iranian"
     * @const
     */
    "iranian": "iranian",
    /**
     * value: "iraqi"
     * @const
     */
    "iraqi": "iraqi",
    /**
     * value: "irish"
     * @const
     */
    "irish": "irish",
    /**
     * value: "israeli"
     * @const
     */
    "israeli": "israeli",
    /**
     * value: "italian"
     * @const
     */
    "italian": "italian",
    /**
     * value: "ivorian"
     * @const
     */
    "ivorian": "ivorian",
    /**
     * value: "jamaican"
     * @const
     */
    "jamaican": "jamaican",
    /**
     * value: "japanese"
     * @const
     */
    "japanese": "japanese",
    /**
     * value: "jordanian"
     * @const
     */
    "jordanian": "jordanian",
    /**
     * value: "kazakhstani"
     * @const
     */
    "kazakhstani": "kazakhstani",
    /**
     * value: "kenyan"
     * @const
     */
    "kenyan": "kenyan",
    /**
     * value: "kittian and nevisian"
     * @const
     */
    "kittian and nevisian": "kittian and nevisian",
    /**
     * value: "kuwaiti"
     * @const
     */
    "kuwaiti": "kuwaiti",
    /**
     * value: "kyrgyz"
     * @const
     */
    "kyrgyz": "kyrgyz",
    /**
     * value: "laotian"
     * @const
     */
    "laotian": "laotian",
    /**
     * value: "latvian"
     * @const
     */
    "latvian": "latvian",
    /**
     * value: "lebanese"
     * @const
     */
    "lebanese": "lebanese",
    /**
     * value: "liberian"
     * @const
     */
    "liberian": "liberian",
    /**
     * value: "libyan"
     * @const
     */
    "libyan": "libyan",
    /**
     * value: "liechtensteiner"
     * @const
     */
    "liechtensteiner": "liechtensteiner",
    /**
     * value: "lithuanian"
     * @const
     */
    "lithuanian": "lithuanian",
    /**
     * value: "luxembourger"
     * @const
     */
    "luxembourger": "luxembourger",
    /**
     * value: "macedonian"
     * @const
     */
    "macedonian": "macedonian",
    /**
     * value: "malagasy"
     * @const
     */
    "malagasy": "malagasy",
    /**
     * value: "malawian"
     * @const
     */
    "malawian": "malawian",
    /**
     * value: "malaysian"
     * @const
     */
    "malaysian": "malaysian",
    /**
     * value: "maldivan"
     * @const
     */
    "maldivan": "maldivan",
    /**
     * value: "malian"
     * @const
     */
    "malian": "malian",
    /**
     * value: "maltese"
     * @const
     */
    "maltese": "maltese",
    /**
     * value: "marshallese"
     * @const
     */
    "marshallese": "marshallese",
    /**
     * value: "mauritanian"
     * @const
     */
    "mauritanian": "mauritanian",
    /**
     * value: "mauritian"
     * @const
     */
    "mauritian": "mauritian",
    /**
     * value: "mexican"
     * @const
     */
    "mexican": "mexican",
    /**
     * value: "micronesian"
     * @const
     */
    "micronesian": "micronesian",
    /**
     * value: "moldovan"
     * @const
     */
    "moldovan": "moldovan",
    /**
     * value: "monacan"
     * @const
     */
    "monacan": "monacan",
    /**
     * value: "mongolian"
     * @const
     */
    "mongolian": "mongolian",
    /**
     * value: "moroccan"
     * @const
     */
    "moroccan": "moroccan",
    /**
     * value: "mosotho"
     * @const
     */
    "mosotho": "mosotho",
    /**
     * value: "motswana"
     * @const
     */
    "motswana": "motswana",
    /**
     * value: "mozambican"
     * @const
     */
    "mozambican": "mozambican",
    /**
     * value: "namibian"
     * @const
     */
    "namibian": "namibian",
    /**
     * value: "nauruan"
     * @const
     */
    "nauruan": "nauruan",
    /**
     * value: "nepalese"
     * @const
     */
    "nepalese": "nepalese",
    /**
     * value: "new zealander"
     * @const
     */
    "new zealander": "new zealander",
    /**
     * value: "ni:vanuatu"
     * @const
     */
    "ni:vanuatu": "ni:vanuatu",
    /**
     * value: "nicaraguan"
     * @const
     */
    "nicaraguan": "nicaraguan",
    /**
     * value: "nigerien"
     * @const
     */
    "nigerien": "nigerien",
    /**
     * value: "north korean"
     * @const
     */
    "north korean": "north korean",
    /**
     * value: "northern irish"
     * @const
     */
    "northern irish": "northern irish",
    /**
     * value: "norwegian"
     * @const
     */
    "norwegian": "norwegian",
    /**
     * value: "omani"
     * @const
     */
    "omani": "omani",
    /**
     * value: "pakistani"
     * @const
     */
    "pakistani": "pakistani",
    /**
     * value: "palauan"
     * @const
     */
    "palauan": "palauan",
    /**
     * value: "panamanian"
     * @const
     */
    "panamanian": "panamanian",
    /**
     * value: "papua new guinean"
     * @const
     */
    "papua new guinean": "papua new guinean",
    /**
     * value: "paraguayan"
     * @const
     */
    "paraguayan": "paraguayan",
    /**
     * value: "peruvian"
     * @const
     */
    "peruvian": "peruvian",
    /**
     * value: "polish"
     * @const
     */
    "polish": "polish",
    /**
     * value: "portuguese"
     * @const
     */
    "portuguese": "portuguese",
    /**
     * value: "qatari"
     * @const
     */
    "qatari": "qatari",
    /**
     * value: "romanian"
     * @const
     */
    "romanian": "romanian",
    /**
     * value: "russian"
     * @const
     */
    "russian": "russian",
    /**
     * value: "rwandan"
     * @const
     */
    "rwandan": "rwandan",
    /**
     * value: "saint lucian"
     * @const
     */
    "saint lucian": "saint lucian",
    /**
     * value: "salvadoran"
     * @const
     */
    "salvadoran": "salvadoran",
    /**
     * value: "samoan"
     * @const
     */
    "samoan": "samoan",
    /**
     * value: "san marinese"
     * @const
     */
    "san marinese": "san marinese",
    /**
     * value: "sao tomean"
     * @const
     */
    "sao tomean": "sao tomean",
    /**
     * value: "saudi"
     * @const
     */
    "saudi": "saudi",
    /**
     * value: "scottish"
     * @const
     */
    "scottish": "scottish",
    /**
     * value: "senegalese"
     * @const
     */
    "senegalese": "senegalese",
    /**
     * value: "serbian"
     * @const
     */
    "serbian": "serbian",
    /**
     * value: "seychellois"
     * @const
     */
    "seychellois": "seychellois",
    /**
     * value: "sierra leonean"
     * @const
     */
    "sierra leonean": "sierra leonean",
    /**
     * value: "singaporean"
     * @const
     */
    "singaporean": "singaporean",
    /**
     * value: "slovakian"
     * @const
     */
    "slovakian": "slovakian",
    /**
     * value: "slovenian"
     * @const
     */
    "slovenian": "slovenian",
    /**
     * value: "solomon islander"
     * @const
     */
    "solomon islander": "solomon islander",
    /**
     * value: "somali"
     * @const
     */
    "somali": "somali",
    /**
     * value: "south african"
     * @const
     */
    "south african": "south african",
    /**
     * value: "south korean"
     * @const
     */
    "south korean": "south korean",
    /**
     * value: "spanish"
     * @const
     */
    "spanish": "spanish",
    /**
     * value: "sri lankan"
     * @const
     */
    "sri lankan": "sri lankan",
    /**
     * value: "sudanese"
     * @const
     */
    "sudanese": "sudanese",
    /**
     * value: "surinamer"
     * @const
     */
    "surinamer": "surinamer",
    /**
     * value: "swazi"
     * @const
     */
    "swazi": "swazi",
    /**
     * value: "swedish"
     * @const
     */
    "swedish": "swedish",
    /**
     * value: "swiss"
     * @const
     */
    "swiss": "swiss",
    /**
     * value: "syrian"
     * @const
     */
    "syrian": "syrian",
    /**
     * value: "taiwanese"
     * @const
     */
    "taiwanese": "taiwanese",
    /**
     * value: "tajik"
     * @const
     */
    "tajik": "tajik",
    /**
     * value: "tanzanian"
     * @const
     */
    "tanzanian": "tanzanian",
    /**
     * value: "thai"
     * @const
     */
    "thai": "thai",
    /**
     * value: "togolese"
     * @const
     */
    "togolese": "togolese",
    /**
     * value: "tongan"
     * @const
     */
    "tongan": "tongan",
    /**
     * value: "trinidadian or tobagonian"
     * @const
     */
    "trinidadian or tobagonian": "trinidadian or tobagonian",
    /**
     * value: "tunisian"
     * @const
     */
    "tunisian": "tunisian",
    /**
     * value: "turkish"
     * @const
     */
    "turkish": "turkish",
    /**
     * value: "tuvaluan"
     * @const
     */
    "tuvaluan": "tuvaluan",
    /**
     * value: "ugandan"
     * @const
     */
    "ugandan": "ugandan",
    /**
     * value: "ukrainian"
     * @const
     */
    "ukrainian": "ukrainian",
    /**
     * value: "uruguayan"
     * @const
     */
    "uruguayan": "uruguayan",
    /**
     * value: "uzbekistani"
     * @const
     */
    "uzbekistani": "uzbekistani",
    /**
     * value: "venezuelan"
     * @const
     */
    "venezuelan": "venezuelan",
    /**
     * value: "vietnamese"
     * @const
     */
    "vietnamese": "vietnamese",
    /**
     * value: "welsh"
     * @const
     */
    "welsh": "welsh",
    /**
     * value: "yemenite"
     * @const
     */
    "yemenite": "yemenite",
    /**
     * value: "zambian"
     * @const
     */
    "zambian": "zambian",
    /**
     * value: "zimbabwean"
     * @const
     */
    "zimbabwean": "zimbabwean"  };

  /**
   * Returns a <code>Nationalities</code> enum value from a Javascript object name.
   * @param {Object} data The plain JavaScript object containing the name of the enum value.
   * @return {module:model/Nationalities} The enum <code>Nationalities</code> value.
   */
  exports.constructFromObject = function(object) {
    return object;
  }

  return exports;
}));


