/**
 * CV4CREW
 * API to fill CV for crewing agencies
 *
 * OpenAPI spec version: 1.0.0
 * Contact: eugene.kondrashev@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 3.3.4
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Error', 'model/Personal'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/Error'), require('../model/Personal'));
  } else {
    // Browser globals (root is window)
    if (!root.Cv4Crew) {
      root.Cv4Crew = {};
    }
    root.Cv4Crew.DefaultApi = factory(root.Cv4Crew.ApiClient, root.Cv4Crew.Error, root.Cv4Crew.Personal);
  }
}(this, function(ApiClient, Error, Personal) {
  'use strict';

  /**
   * Default service.
   * @module api/DefaultApi
   * @version 1.0.0
   */

  /**
   * Constructs a new DefaultApi. 
   * @alias module:api/DefaultApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the getPersonalDetails operation.
     * @callback module:api/DefaultApi~getPersonalDetailsCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Personal} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get Personal Details
     * Route to get seaman personal details information
     * @param {module:api/DefaultApi~getPersonalDetailsCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Personal}
     */
    this.getPersonalDetails = function(callback) {
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['BearerAuth'];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = Personal;

      return this.apiClient.callApi(
        '/profile/personal', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the putPersonalDetails operation.
     * @callback module:api/DefaultApi~putPersonalDetailsCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Update Personal Details
     * Route to update seaman personal details information
     * @param {Object} opts Optional parameters
     * @param {module:model/Personal} opts.personal 
     * @param {module:api/DefaultApi~putPersonalDetailsCallback} callback The callback function, accepting three arguments: error, data, response
     */
    this.putPersonalDetails = function(opts, callback) {
      opts = opts || {};
      var postBody = opts['personal'];


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['BearerAuth'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = null;

      return this.apiClient.callApi(
        '/profile/personal', 'PUT',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
