/**
 * CV4CREW
 * API to fill CV for crewing agencies
 *
 * OpenAPI spec version: 1.0.0
 * Contact: eugene.kondrashev@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 3.3.4
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Cv4Crew);
  }
}(this, function(expect, Cv4Crew) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Cv4Crew.Names();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Names', function() {
    it('should create an instance of Names', function() {
      // uncomment below and update the code to test Names
      //var instance = new Cv4Crew.Names();
      //expect(instance).to.be.a(Cv4Crew.Names);
    });

    it('should have the property first (base name: "first")', function() {
      // uncomment below and update the code to test the property first
      //var instance = new Cv4Crew.Names();
      //expect(instance).to.be();
    });

    it('should have the property second (base name: "second")', function() {
      // uncomment below and update the code to test the property second
      //var instance = new Cv4Crew.Names();
      //expect(instance).to.be();
    });

    it('should have the property middle (base name: "middle")', function() {
      // uncomment below and update the code to test the property middle
      //var instance = new Cv4Crew.Names();
      //expect(instance).to.be();
    });

  });

}));
