/**
 * CV4CREW
 * API to fill CV for crewing agencies
 *
 * OpenAPI spec version: 1.0.0
 * Contact: eugene.kondrashev@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 3.3.4
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Cv4Crew);
  }
}(this, function(expect, Cv4Crew) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Cv4Crew.Personal();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Personal', function() {
    it('should create an instance of Personal', function() {
      // uncomment below and update the code to test Personal
      //var instance = new Cv4Crew.Personal();
      //expect(instance).to.be.a(Cv4Crew.Personal);
    });

    it('should have the property names (base name: "names")', function() {
      // uncomment below and update the code to test the property names
      //var instance = new Cv4Crew.Personal();
      //expect(instance).to.be();
    });

    it('should have the property gender (base name: "gender")', function() {
      // uncomment below and update the code to test the property gender
      //var instance = new Cv4Crew.Personal();
      //expect(instance).to.be();
    });

    it('should have the property birth (base name: "birth")', function() {
      // uncomment below and update the code to test the property birth
      //var instance = new Cv4Crew.Personal();
      //expect(instance).to.be();
    });

    it('should have the property nationality (base name: "nationality")', function() {
      // uncomment below and update the code to test the property nationality
      //var instance = new Cv4Crew.Personal();
      //expect(instance).to.be();
    });

    it('should have the property residence (base name: "residence")', function() {
      // uncomment below and update the code to test the property residence
      //var instance = new Cv4Crew.Personal();
      //expect(instance).to.be();
    });

    it('should have the property citizenship (base name: "citizenship")', function() {
      // uncomment below and update the code to test the property citizenship
      //var instance = new Cv4Crew.Personal();
      //expect(instance).to.be();
    });

    it('should have the property marital (base name: "marital")', function() {
      // uncomment below and update the code to test the property marital
      //var instance = new Cv4Crew.Personal();
      //expect(instance).to.be();
    });

    it('should have the property military (base name: "military")', function() {
      // uncomment below and update the code to test the property military
      //var instance = new Cv4Crew.Personal();
      //expect(instance).to.be();
    });

  });

}));
