/**
 * CV4CREW
 * API to fill CV for crewing agencies
 *
 * OpenAPI spec version: 1.0.0
 * Contact: eugene.kondrashev@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 3.3.4
 *
 * Do not edit the class manually.
 *
 */

(function(factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Birth', 'model/Citizenship', 'model/Countries', 'model/Error', 'model/Genders', 'model/Marital', 'model/Military', 'model/Names', 'model/Nationalities', 'model/Personal', 'model/Residence', 'api/DefaultApi'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('./ApiClient'), require('./model/Birth'), require('./model/Citizenship'), require('./model/Countries'), require('./model/Error'), require('./model/Genders'), require('./model/Marital'), require('./model/Military'), require('./model/Names'), require('./model/Nationalities'), require('./model/Personal'), require('./model/Residence'), require('./api/DefaultApi'));
  }
}(function(ApiClient, Birth, Citizenship, Countries, Error, Genders, Marital, Military, Names, Nationalities, Personal, Residence, DefaultApi) {
  'use strict';

  /**
   * API_to_fill_CV_for_crewing_agencies.<br>
   * The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
   * <p>
   * An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
   * <pre>
   * var Cv4Crew = require('index'); // See note below*.
   * var xxxSvc = new Cv4Crew.XxxApi(); // Allocate the API class we're going to use.
   * var yyyModel = new Cv4Crew.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
   * and put the application logic within the callback function.</em>
   * </p>
   * <p>
   * A non-AMD browser application (discouraged) might do something like this:
   * <pre>
   * var xxxSvc = new Cv4Crew.XxxApi(); // Allocate the API class we're going to use.
   * var yyy = new Cv4Crew.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * </p>
   * @module index
   * @version 1.0.0
   */
  var exports = {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient: ApiClient,
    /**
     * The Birth model constructor.
     * @property {module:model/Birth}
     */
    Birth: Birth,
    /**
     * The Citizenship model constructor.
     * @property {module:model/Citizenship}
     */
    Citizenship: Citizenship,
    /**
     * The Countries model constructor.
     * @property {module:model/Countries}
     */
    Countries: Countries,
    /**
     * The Error model constructor.
     * @property {module:model/Error}
     */
    Error: Error,
    /**
     * The Genders model constructor.
     * @property {module:model/Genders}
     */
    Genders: Genders,
    /**
     * The Marital model constructor.
     * @property {module:model/Marital}
     */
    Marital: Marital,
    /**
     * The Military model constructor.
     * @property {module:model/Military}
     */
    Military: Military,
    /**
     * The Names model constructor.
     * @property {module:model/Names}
     */
    Names: Names,
    /**
     * The Nationalities model constructor.
     * @property {module:model/Nationalities}
     */
    Nationalities: Nationalities,
    /**
     * The Personal model constructor.
     * @property {module:model/Personal}
     */
    Personal: Personal,
    /**
     * The Residence model constructor.
     * @property {module:model/Residence}
     */
    Residence: Residence,
    /**
     * The DefaultApi service constructor.
     * @property {module:api/DefaultApi}
     */
    DefaultApi: DefaultApi
  };

  return exports;
}));
